{% set name = "py4dstem" %}
{% set version = "0.14.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/py4DSTEM/py4DSTEM-{{ version }}.tar.gz
  sha256: 30b241e50802f3cf5ce5cc0ee856bcc85e90ecbfd449bdc9b701a00108044268

build:
  number: 0
  noarch: python
  entry_points:
    - py4DSTEM=py4DSTEM.gui.runGUI:launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python <3.12,>=3.9
  run:
    - python <3.12,>=3.9
    - numpy >=1.19
    - scipy >=1.5.2
    - h5py >=3.2.0
    - hdf5plugin >=4.1.3
    - ncempy >=1.8.1
    - matplotlib-base >=3.4.2
    - scikit-image >=0.17.2
    - scikit-learn >=0.23.2
    - scikit-optimize >=0.9.0
    - tqdm >=4.46.1
    - dill >=0.3.3
    - gdown >=4.4.0
    - dask-core >=2.3.0
    - distributed >=2.3.0
    - emdfile >=0.0.11
    - mpire
    - colorspacious

test:
  imports:
    - py4DSTEM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/py4DSTEM/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: An open source python package for processing and analysis of 4D STEM data.

  description: |
    py4DSTEM is a python tool for analysis of four-dimensional scanning 
    transimission electron microscopy (4D-STEM) data. 
  doc_url: https://github.com/py4dstem/py4DSTEM
  dev_url: https://github.com/py4dstem/py4DSTEM

extra:
  recipe-maintainers:
    - sezelt
    - jan-janssen
