{% set name = "py4dstem" %}
{% set version = "0.14.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py4DSTEM-{{ version }}.tar.gz
  sha256: 5b28897c01bf768e970f38fd96bc836972e1a5c572d39549ff9b3eee79015fc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - pip
  run:
    - python >=3.9,<3.12
    - numpy >=1.19
    - scipy >=1.5.2
    - h5py >=3.2.0
    - hdf5plugin >=4.1.3
    - ncempy >=1.8.1
    - matplotlib-base >=3.2.2
    - scikit-image >=0.17.2
    - scikit-learn >=0.23.2
    - scikit-optimize >=0.9.0
    - tqdm >=4.46.1
    - dill >=0.3.3
    - gdown >=4.7.1
    - dask-core >=2.3.0
    - distributed >=2.3.0
    - emdfile >=0.0.14
    - mpire >=2.7.1
    - threadpoolctl >=3.1.0
    - pylops >=2.1.0
    - colorspacious >=1.1.2

test:
  imports:
    - py4DSTEM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/py4DSTEM/
  summary: An open source python package for processing and analysis of 4D STEM data.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  description: |
    py4DSTEM is a python tool for analysis of four-dimensional scanning 
    transimission electron microscopy (4D-STEM) data. 
  doc_url: https://github.com/py4dstem/py4DSTEM
  dev_url: https://github.com/py4dstem/py4DSTEM

extra:
  recipe-maintainers:
    - sezelt
    - jan-janssen
