{% set name = "py4dstem" %}
{% set version = "0.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/py4DSTEM/py4DSTEM-{{ version }}.tar.gz
  sha256: 23149345520e508ac5288e512f868843243434788cda9279aca1314730c1b29b

build:
  number: 0
  noarch: python
  entry_points:
    - py4DSTEM=py4DSTEM.gui.runGUI:launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py >=2.10.0
    - ipywidgets
    - ncempy >=1.6.0
    - numba >=0.49.1
    - numpy >=1.15
    - pymatgen
    - pyqt >=5.9
    - pyqtgraph >=0.10
    - python >=3.6
    - qtconsole >=4.4
    - scikit-image >=0.16.2
    - scikit-learn >=0.22.1
    - scipy >=1.1
    - tqdm

test:
  imports:
    - py4DSTEM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/py4DSTEM/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: An open source python package for processing and analysis of 4D STEM data.

  description: |
    py4DSTEM is a python tool for analysis of four-dimensional scanning 
    transimission electron microscopy (4D-STEM) data. 
  doc_url: https://github.com/py4dstem/py4DSTEM
  dev_url: https://github.com/py4dstem/py4DSTEM

extra:
  recipe-maintainers:
    - jan-janssen
