{% set name = "py4dstem" %}
{% set version = "0.12.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/py4dstem/py4DSTEM.git
  git_tag: origin/main
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  noarch: python
  entry_points:
    - py4DSTEM=py4DSTEM.gui.runGUI:launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dask >=2.3.0
    - distributed >=2.3.0
    - h5py >=2.10.0
    - ipywidgets >=7.6.3
    - matplotlib >=3.4.2
    - ncempy >=1.8.1
    - numpy >=1.19
    - pyqt >=5.10
    - pyqtgraph >=0.11
    - python >=3.7
    - qtconsole >=4.7.7
    - scikit-image >=0.17.2
    - scikit-learn >=0.23.2
    - scipy >=1.5.2
    - tqdm >=4.46.1
    - dill >=0.3.3
    - requests >=2.25.1

test:
  imports:
    - py4DSTEM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/py4DSTEM/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: An open source python package for processing and analysis of 4D STEM data.

  description: |
    py4DSTEM is a python tool for analysis of four-dimensional scanning 
    transimission electron microscopy (4D-STEM) data. 
  doc_url: https://github.com/py4dstem/py4DSTEM
  dev_url: https://github.com/py4dstem/py4DSTEM

extra:
  recipe-maintainers:
    - jan-janssen
    - sezelt
