{% set name = "py4dstem" %}
{% set version = "0.13.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/py4DSTEM/py4DSTEM-{{ version }}.tar.gz
  sha256: ba60fe6564dd171d782a83a4f2d1ed190668142b221fdca9f237ac3fbfdb8dcd

build:
  number: 0
  noarch: python
  entry_points:
    - py4DSTEM=py4DSTEM.gui.runGUI:launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy >=1.19
    - scipy >=1.5.2
    - h5py >=3.2.0
    - ncempy >=1.8.1
    - matplotlib-base >=3.4.2
    - scikit-image >=0.17.2
    - scikit-learn >=0.23.2
    - pyqt >=5.10
    - pyqtgraph >=0.11
    - qtconsole >=4.7.7
    - ipywidgets >=7.6.3
    - tqdm >=4.46.1
    - dill >=0.3.3
    - gdown >=4.4.0
    - dask-core >=2.3.0
    - distributed >=2.3.0

test:
  imports:
    - py4DSTEM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/py4DSTEM/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: An open source python package for processing and analysis of 4D STEM data.

  description: |
    py4DSTEM is a python tool for analysis of four-dimensional scanning 
    transimission electron microscopy (4D-STEM) data. 
  doc_url: https://github.com/py4dstem/py4DSTEM
  dev_url: https://github.com/py4dstem/py4DSTEM

extra:
  recipe-maintainers:
    - sezelt
    - jan-janssen
